services:
  postgres:
    image: postgres:16
    container_name: ds-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ds_postgres_data:/var/lib/postgresql/data

volumes:
  ds_postgres_data: